# Generated by Django 5.0.1 on 2024-02-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='minium_age',
            new_name='minimum_age',
        ),
    ]
